name: Bug 报告
description: 报告主题中的错误或显示问题
labels:
  - bug
assignees:
  - caolib
body:
  - type: input
    id: theme_version
    attributes:
      label: 主题版本
      placeholder: v1.2.3
    validations:
      required: true
  - type: input
    id: typora_version
    attributes:
      label: Typora 编辑器版本
      placeholder: v1.8.7
    validations:
      required: false
  - type: dropdown
    id: platform
    attributes:
      label: 系统
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: 错误描述
      placeholder: 例如：xxx 功能无法正常显示，最好附加截图和markdown代码
    validations:
      required: true
